version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - backend/.env 
    volumes:
      - ./backend:/app 

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - ./mongo-data:/data/db 
      
